name: CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest]
        gcc: [7, 8, 9]
    
    steps:
    - uses: actions/checkout@v1
    - name: setup-linux
      if: contains(matrix.os, 'ubuntu')
      run: |
        sudo apt-get update && \
        sudo apt-get install software-properties-common ; \
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test && \
        sudo apt-get update && \
        sudo apt-get install -y cmake gcc-${GCC_V} g++-${GCC_V} gfortran-${GCC_V} && \
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-${GCC_V} 100 \
        --slave /usr/bin/g++ g++ /usr/bin/g++-${GCC_V} \
        --slave /usr/bin/gfortran gfortran /usr/bin/gfortran-${GCC_V} \
        --slave /usr/bin/gcov gcov /usr/bin/gcov-${GCC_V} && \
        gcc --version && gfortran --version && cmake --version
      env:
        GCC_V: ${{ matrix.gcc }}
    - name: setup-macos
      if: contains( matrix.os, 'macos')
      run: |
        brew install gcc@${GCC_V} || brew upgrade gcc@{GCC_V} && \
        gcc-${GCC_V} --version && gfortran-${GCC_V} --version && cmake --version
      env:
        GCC_V: ${{ matrix.gcc }}
#    - name: configure
#      run: cmake -Wdev -S ${GITHUB_WORKSPACE} -B .
#      working-directory: ./build
#      env:
#        FC: gfortran-${{ matrix.gcc }}
#        CC: gcc-${{ matrix.gcc }}
#        CXX: g++-${{ matrix.gcc }}
#    - name: make
#      run: make
